### ISSUE TITLE
SloppyCell import

### ISSUE THREAD

**Issue by ljschumacher** [EmoryUniversityTheoreticalBiophysics/SirIsaac#16]
Trying to run simpleExample

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-498ecca7912c> in <module>
      1 import scipy, pylab
----> 2 import FittingProblem
      3 get_ipython().run_line_magic('matplotlib', 'inline')

/Library/Python/2.7/site-packages/SirIsaac/FittingProblem.py in <module>
     14 SIRISAACDIR = '/Library/Python/2.7/site-packages/SirIsaac/'
     15 
---> 16 from SloppyCell.ReactionNetworks import *
     17 import PowerLawNetwork
     18 reload(PowerLawNetwork)

ModuleNotFoundError: No module named 'SloppyCell'`

Not sure if this is an installation issue, since `import SloppyCell` works in ipython.

I'm also trying to run it in python 3 and have change all prints and Exceptions, and not sure if the above is python 3 related?

EDIT: `python SloppyCellTest.py` ran fine in python 2, but obviously with python3 it fails for the above reason

**Comment by bcdaniels** [comment]
Thanks for the feedback.  It looks like this is an issue with Python 3, which we do not currently support (but it's on our to-do list: see #12).  Until then, you might try either installing everything with Python 3 (including SloppyCell, though I'm not sure this is possible) or everything with Python 2 (which should work, but you'd have to also run Sir Isaac in Python 2).

**Comment by bcdaniels** [comment]
SirIsaac is now updated to run in python 3 (#29), which should fix this issue.  I will close this for now with the assumption that this issue is now resolved, but let me know if it still doesn't work.
