### ISSUE TITLE
simpleExample not working

### ISSUE THREAD

**Issue by ljschumacher** [EmoryUniversityTheoreticalBiophysics/SirIsaac#18]
running the jupyter notebook, at the "Analyze the selected model" stage, after `p.plotBestModelResults(plotInitialConditions=True,indices=range(10));`
I get the following error
`WARNING:daskr:
WARNING:daskr:The matrix of partial derivatives is singular, with the use of the direct methods. Some of your equations may be redundant. DDASKR cannot solve the problem as stated. It is possible that the redundant equations could be removed, and then DDASKR could solve the problem. It is also possible that a solution to your problem either does not exist or is not unique. (IDID=-8)
WARNING:ReactionNetworks.Dynamics:Integration ended prematurely in network PowerLaw_Network on node 0.`

**Comment by bcdaniels** [comment]
Hi—this is a known issue with the current `master` branch (see issue #7).  Until this fix is merged into the `master` branch, please either use the `develop` branch or see #7 for a workaround.

**Comment by bcdaniels** [comment]
This was fixed by #15.
